# Generated by Django 3.2 on 2023-07-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0007_auto_20200325_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cqnt',
            field=models.IntegerField(null=True),
        ),
    ]
